### ISSUE TITLE
Missing `bin/redis_exporter`

### ISSUE THREAD

**Issue by marceloneppel** [canonical/redis-k8s-operator#87]
## Steps to reproduce

1. juju deploy redis-k8s --channel edge

## Expected behavior
No error in the Juju debug logs.

## Actual behavior

The charm shows an error related to not being able to start `bin/redis_exporter`.

## Versions

Operating system: Ubuntu 24.04 LTS

Juju CLI: 3.5.1

Juju agent: 3.5.1

Charm revision: 29

microk8s: v1.30.0

## Log output

Juju debug log: 

```sh
unit-redis-k8s-0: 14:28:40 ERROR unit.redis-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 723, in <module>
    main(RedisK8sCharm)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 106, in _redis_pebble_ready
    self._update_layer()
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 352, in _update_layer
    container.restart("redis", "redis_exporter")
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/model.py", line 1893, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/pebble.py", line 1638, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/pebble.py", line 1659, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "redis_exporter" (cannot start service: fork/exec bin/redis_exporter: no such file or directory)
----- Logs from task 0 -----
2024-06-12T14:28:39Z INFO Service "redis" has never been started.
----- Logs from task 1 -----
2024-06-12T14:28:39Z INFO Service "redis_exporter" has never been started.
----- Logs from task 3 -----
2024-06-12T14:28:40Z ERROR cannot start service: fork/exec bin/redis_exporter: no such file or directory
-----
unit-redis-k8s-0: 14:28:41 ERROR juju.worker.uniter.operation hook "redis-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-redis-k8s-0: 14:28:41 ERROR juju.worker.uniter pebble poll failed for container "redis": failed to send pebble-ready event: hook failed
```

## Additional context

Revision 28 is working correctly.

**Comment by codethulu** [comment]
Hi, also ran into this issue.

In the [release workflow](https://github.com/canonical/redis-k8s-operator/blob/e9bdad913a46d4dd36abb0d4bef3e9026de27e8d/.github/workflows/release.yaml#L44) the redis-image is pinned to revision 3. This means that the updated image is not uploaded, and the`redis_exporter` is not found.

If the correct (upstream) image is pinned, I think this should solve this bug, since the integration tests are working fine.

**Comment by reneradoi** [comment]
https://github.com/canonical/redis-k8s-operator/pull/88

**Comment by reneradoi** [comment]
It has been fixed with revision 31: `juju deploy redis-k8s --channel edge` will give you the required image now.

**Comment by marceloneppel** [comment]
Thanks, @reneradoi!
