### ISSUE TITLE
Error in revision 35. hook failed: "redis-relation-created" because current_master is None.

### ISSUE THREAD

**Issue by javierdelapuente** [canonical/redis-k8s-operator#97]
## Steps to reproduce

1. juju deploy redis-k8s --channel=latest/edge
2. juju integrate
## Expected behavior
It works.

## Actual behavior

```
ubuntu@paas-app-charmer:~$ juju status
Model    Controller  Cloud/Region        Version  SLA          Timestamp
testing  microk8s    microk8s/localhost  3.5.3    unsupported  16:50:50+02:00

App        Version  Status  Scale  Charm      Channel      Rev  Address         Exposed  Message
flask-k8s           active      1  flask-k8s                 0  10.152.183.254  no       
redis-k8s           error     1/0  redis-k8s  latest/edge   35  10.152.183.129  no       hook failed: "redis-relation-created"

Unit          Workload  Agent  Address      Ports  Message
flask-k8s/0*  active    idle   10.1.46.205         
redis-k8s/0*  error     idle   10.1.46.231         hook failed: "redis-relation-created"
```

## Versions

Operating system: 

Juju CLI: 
3.5.3-genericlinux-amd64

Juju agent: 
3.5.3

Charm revision: 35

microk8s: MicroK8s v1.29.8 revision 7144

## Log output

Juju debug log: 

```
unit-redis-k8s-0: 16:37:40 ERROR unit.redis-k8s/0.juju-log redis:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 750, in <module>
    main(RedisK8sCharm)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 312, in _on_redis_relation_created
    event.relation.data[self.app][LEADER_HOST_KEY] = self.current_master
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/model.py", line 1474, in __setitem__
    self._validate_write(key, value)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/model.py", line 1440, in _validate_write
    raise RelationDataTypeError(
ops.model.RelationDataTypeError: relation data values must be strings, not <class 'NoneType'>

```

**Comment by reneradoi** [comment]
Hello @javierdelapuente !

Thank you for reporting this issue. I wanted to reproduce it but could not find how to integrate `redis-k8s` and `flask-k8s`. The error says that `flask-k8s` doesn't have a redis interface. Could you please provide the full information in "steps to reproduce"?

As a workaround I've tested with some other operators that support the redis interface, e.g. `superset-k8s`. Integrating both worked without failing.

**Comment by javierdelapuente** [comment]
> Hello @javierdelapuente !
> 
> Thank you for reporting this issue. I wanted to reproduce it but could not find how to integrate `redis-k8s` and `flask-k8s`. The error says that `flask-k8s` doesn't have a redis interface. Could you please provide the full information in "steps to reproduce"?
> 
> As a workaround I've tested with some other operators that support the redis interface, e.g. `superset-k8s`. Integrating both worked without failing.

Hi @reneradoi!  sorry for not being specific, that was part of an integration test.

I can reproduce it in my machine following this tutorial: https://charmhub.io/netbox/docs/tutorial-getting-started.

I think that if redis has some time to settle before creating the integration it works, but if you run the integration just after deploying redis it will most likely get into an error state (forever).

```
ubuntu@paas-app-charmer:~$ juju status --relations
Model            Controller  Cloud/Region        Version  SLA          Timestamp
netbox-tutorial  microk8s    microk8s/localhost  3.5.3    unsupported  11:08:18+02:00

App        Version  Status   Scale  Charm      Channel        Rev  Address         Exposed  Message
netbox              blocked      1  netbox     latest/stable   19  10.152.183.248  no       missing integrations: postgresql, redis, s3
redis-k8s           error        1  redis-k8s  latest/edge     35  10.152.183.50   no       hook failed: "redis-relation-created"

Unit          Workload  Agent  Address      Ports  Message
netbox/0*     blocked   idle   10.1.46.232         missing integrations: postgresql, redis, s3
redis-k8s/0*  error     idle   10.1.46.203         hook failed: "redis-relation-created" for netbox:redis

Integration provider   Requirer               Interface       Type     Message
netbox:secret-storage  netbox:secret-storage  secret-storage  peer     
redis-k8s:redis        netbox:redis           redis           regular  
redis-k8s:redis-peers  redis-k8s:redis-peers  redis-peers     peer     
```

```
unit-redis-k8s-0: 11:04:46 INFO juju.worker.uniter found queued "install" hook
unit-redis-k8s-0: 11:04:47 INFO unit.redis-k8s/0.juju-log Running legacy hooks/install.
unit-redis-k8s-0: 11:04:47 WARNING unit.redis-k8s/0.juju-log 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-redis-k8s-0: 11:04:47 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)
unit-redis-k8s-0: 11:04:47 WARNING unit.redis-k8s/0.juju-log redis:2: 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-redis-k8s-0: 11:04:47 WARNING unit.redis-k8s/0.juju-log redis:2: DEPRECATION WARNING - `redis` interface is a legacy interface.
unit-redis-k8s-0: 11:04:47 ERROR unit.redis-k8s/0.juju-log redis:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 750, in <module>
    main(RedisK8sCharm)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/./src/charm.py", line 312, in _on_redis_relation_created
    event.relation.data[self.app][LEADER_HOST_KEY] = self.current_master
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/model.py", line 1474, in __setitem__
    self._validate_write(key, value)
  File "/var/lib/juju/agents/unit-redis-k8s-0/charm/venv/ops/model.py", line 1440, in _validate_write
    raise RelationDataTypeError(
ops.model.RelationDataTypeError: relation data values must be strings, not <class 'NoneType'>
unit-netbox-0: 11:04:47 INFO unit.netbox/0.juju-log redis:2: pebble client in the django container is not ready
unit-redis-k8s-0: 11:04:48 ERROR juju.worker.uniter.operation hook "redis-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by reneradoi** [comment]
Thank you @javierdelapuente for providing additional information. You are right, if the integration is happening directly after deploying redis (meaning before it has started up), the issue can be reproduced.

**Comment by reneradoi** [comment]
Fix has been provided in revision 36.
